apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  name: gpt-oss-20b
  namespace: external-models
  annotations:
    openshift.io/display-name: "OpenAI/gpt-oss-20b"
    openshift.io/description: " External gpt-oss-20b model"
spec:
  modelRef:
    kind: ExternalModel
    name: gpt-oss-20b
