apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: maas-inference-a-upstream-tls
  namespace: openshift-ingress
spec:
  host: ${MAAS_INFERENCE_CLUSTER_A_HOST}
  exportTo:
    - "."
  workloadSelector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: maas-default-gateway
  trafficPolicy:
    tls:
      mode: SIMPLE
      credentialName: maas-inference-a-upstream-ca
      sni: ${MAAS_INFERENCE_CLUSTER_A_HOST}
      subjectAltNames:
        - ${MAAS_INFERENCE_CLUSTER_A_HOST}
