---
apiVersion: v1
kind: Secret
metadata:
  name: rhdp-maas-credentials
  namespace: external-models
  labels:
    inference.llm-d.ai/ipp-managed: "true"
type: Opaque
stringData:
  api-key: "${MAAS_RHDM_API_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: maas-inference-cluster-a-credentials
  namespace: external-models
  labels:
    inference.llm-d.ai/ipp-managed: "true"
type: Opaque
stringData:
  api-key: "${MAAS_INFERENCE_CLUSTER_A_TOKEN}"