---
apiVersion: inference.opendatahub.io/v1alpha1
kind: ExternalProvider
metadata:
  name: rhdp-external-provider
  namespace: external-models
spec:
  provider: openai
  endpoint: ${MAAS_RHDP_HOST}
  auth:
    type: apikey
    secretRef:
      name: rhdp-maas-credentials
      namespace: external-models
---
apiVersion: inference.opendatahub.io/v1alpha1
kind: ExternalProvider
metadata:
  name: maas-inference-cluster-a-provider
  namespace: external-models
spec:
  provider: openai
  endpoint: ${MAAS_INFERENCE_CLUSTER_A_HOST}
  auth:
    type: apikey
    secretRef:
      name: maas-inference-cluster-a-credentials
      namespace: external-models
